### ISSUE TITLE
bug: no way to scroll groups when width of groups exceeds add-in bar width

### ISSUE THREAD

**Issue by boldcompany** [IIUJ-KrzysztofDawidowicz/Tab-Group-Bar#11]
Currently, if the width of all combined groups exceeds the add-in bar width, additional groups simply go "off-screen" without any way to scroll to them or otherwise access them.

Functionality needed: A way to scroll to the groups that are not shown in the current browser width.

**Comment by IIUJ-KrzysztofDawidowicz** [comment]
Resolved
