### ISSUE TITLE
Downloaded the zip for Tab-Group-Bar

### ISSUE THREAD

**Issue by silat** [IIUJ-KrzysztofDawidowicz/Tab-Group-Bar#19]
Now what do I do with it?:) 
I have no idea how to install it in FF 28?

Please keep updating this add-on. You are on to something good here. If you tune it up I am willing to pay $10 for your hard work:)

**Comment by IIUJ-KrzysztofDawidowicz** [comment]
Unpack the zip and drag the .xpi file onto Firefox.

**Comment by silat** [comment]
But there is no xpi in download  1.4.3 . 
https://github.com/IIUJ-KrzysztofDawidowicz/Tab-Group-Bar/releases
          Thanks
